name: "Build NixOS ISOs"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05-small
      - run: nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso-builder.nix
      - uses: actions/upload-artifact@v3
        with:
          name: nixos-stable-iso
          path: result/iso/nixos-22.05*.iso
          if-no-files-found: error
